
# colleges[""]["comments"][1] = {"name" : "", "comment" : "", "rating" : }
def call_samples(colleges):
    colleges["UC Berkeley"]["comments"][1] = {"name" : "Hau Nguyen","image" : "/static/people/hau.jpg", "comment" : "Berkeley is tough, not going to lie. I'm always struggling and constantly going through a lot of stress, but it's all worth it. The people you meet here, the experience you get, the amazing opportunities you can enrich yourself in, it makes all the hardship seem like nothing.", "rating" : 4}
    colleges["UC Berkeley"]["comments"][2] = {"name" : "Jennifer Nguyen","image" : "/static/people/Jennifer.jpg", "comment" : "I will begin by saying this: Berkeley is HARD. You will be challenged on a daily basis to stretch the boundaries of your understanding, and there will be little time to sit on your laurels and rest. That being said, if you maintain a reasonable courseload and a reasonable set of study habits, you can succeed.", "rating" :4.2}
    colleges["UC Berkeley"]["comments"][3] = {"name" : "Juliet Tran","image" : "/static/people/juliet.jpg", "comment" : "If you're worried about fitting in at a big school, don't. When you're in a community at Berkeley, you find yourself running into people you know on campus constantly, to the point where the school doesn't feel that big at all.", "rating" :4 }

    colleges["UC Davis"]["comments"][1] = {"name" : "Nathan Yngoc","image" : "/static/people/Nate.jpg", "comment" : "Davis is to many people and myself the culture shock because of diversity present. My experience has been met by both the unfriendly and the hyperfriendly. And the both brilliant to the common folk like myself. Reguardless of social tag, it is nice to be surrounded by people with unique expereince and expertise who open my eyes to real world.", "rating" : 4.3 }
    colleges["UC Davis"]["comments"][2] = {"name" : "Shannon Lal","image" : "/static/people/Shan.jpg", "comment" : "Don't under estimate Davis, just because we aren't in a big city, we have so many clubs that will build social ties with people! You'll never feel alone in Davis, sorta feels like a big family. ", "rating" :4.5 }
    colleges["UC Davis"]["comments"][3] = {"name" : "Alan Sani","image" : "/static/people/alan.jpg", "comment" : "My experience was excellent. You have to work the school and take advantage of all it has to offer. If people did not enjoy their experience then they let the school work them in my opinion. I have been more successful than my friends who graduated from Yale, Cal, UCLA, and UCSD.", "rating" :4 }

    colleges["San Jose State"]["comments"][1] = {"name" : "Mikhaela Francisco","image" : "/static/people/meeks.jpg", "comment" : "For someone whose of thinking og going here, I would say that a lot of the experiences are always based on how involved you are around teh campus. There is so many organizations offered and everyone somehow how fits in either way.", "rating" :4}
    colleges["San Jose State"]["comments"][2] = {"name" : "Gabby Swanson","image" : "/static/people/gabby.jpg", "comment" : "The beauty of SJSU is that it is in the bay area. The bay area is very diverse and SJSU is diverse, with the diversity of the students, classes, and organizations. Everyone can find where they belong. Being with the people here, different classes and organizaions, every experience is different.", "rating" :4}
    colleges["San Jose State"]["comments"][3] = {"name" : "Angelica Hayes","image" : "/static/people/angel.jpg", "comment" : "This school is super amazing! I wouldn't want to pick any other. The people here are great, the classes are okay, and the extra-cirricular activities are just outstanding. Come to SJ!", "rating" :4}

    colleges["San Diego State"]["comments"][1] = {"name" : "Matthew Arreola","image" : "/static/people/matt.jpg", "comment" : "SDSU is a great school. From a rigorous, but well paced semester system, to the extra cirriculars, SDSU offers a wide range of opportunites that will allow type of student to florish. Lol. In addition, from the beaches, to the night life, there is always something to do here.", "rating" :4}
    colleges["San Diego State"]["comments"][2] = {"name" : "Francis Neal","image" : "/static/people/Francis.jpg", "comment" : "My current expereince at SDSU is positive. Overall, this is a very good school academically, and the atmosphere at SDSU is sort of enhanced by student life(like clubs and Greek like). I have met so many great people and have had a lot of good experiences since attending this university. ", "rating" :4}
    colleges["San Diego State"]["comments"][3] = {"name" : "Eric Snow","image" : "/static/people/ericSnow.jpg", "comment" : "I would tell students that it is positively different from my expectations. I would also note that is a great mix of both a big and small college, depending on what you make out of it. I went in with the idea of transfering out soon, but now I 've seen how diverse the campus is. This school meets my expectations, but there are things to consider. ", "rating" :4 }

    colleges["CSU Monterey Bay"]["comments"][1] = {"name" : "Erick Acedo","image" : "/static/people/erick.JPG", "comment" : "If you like the pacific breeze, the bipolar weather, and a community that does not discriminate then CSUMB is the school for you! I know that we may be small and not have your expectations, but with the community and opportunities we deliver, it can really change your envisionment of this campus.", "rating" :3.2}
    colleges["CSU Monterey Bay"]["comments"][2] = {"name" : "Elijah Baird","image" : "/static/people/elijah.jpg", "comment" : "It is a small school and the classrooms are, also, smal, so it is easy to talk to your professors and make connections with them, which would be less likely if you were to attend a larger school. I would prefer the over-cast that Monterey exists in. All the faculty that I've met have been dedicated to helping the students.", "rating" :3.5 }
    colleges["CSU Monterey Bay"]["comments"][3] = {"name" : "Sam Antha","image" : "/static/people/sam.JPG", "comment" : "My experience here is very open. You just have to take initiative. It's easy to change your major here, the cost of the school is very affordable.", "rating" :3.5 }

    colleges["UC Irvine"]["comments"][1] = {"name" : "Howard Lam","image" : "/static/people/howardLam.jpg", "comment" : "I think this school is pretty decent and chill. The community is good I think and the school is pretty new so the campus is nice. It is 15 minutes away from the beach and close enough to LA, which means lots of food choices. It is a good community for Asians too if that is what you are looking for.", "rating" :4 }
    colleges["UC Irvine"]["comments"][2] = {"name" : "Ethan Liu","image" : "/static/people/ethanLiu.jpg", "comment" : "UCI is a place that is just good for a wide range of people in general and that there is a place for everyone here. Since there is a good diversity, it is easy to feel at home no matter who you are. ", "rating" :4 }
    colleges["UC Irvine"]["comments"][3] = {"name" : "Danny Chung","image" : "/static/people/danny.jpg", "comment" : "This school has a lot of food choices around which is always a plus. There is a good diversity in clubs and population too which makes it easy to find out something to do or someone to be friends with.", "rating" :4 }
    
    return colleges